compliance:
  - GDPR

data_sensitivity: public

project_type: wordpress-plugin

development_status: active

license: gpl-2.0

audience:
  - travel-agencies
  - developers
  - tour-operators

tech_stack:
  - PHP
  - WordPress
  - Wetu API

version: 1.0.0

documentation_url: https://lsx.design/docs/wetu-importer

support_url: https://lightspeedwp.agency/support

project_priority: optional
